version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-network

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: ./docker/Dockerfile.dev
      args:
        AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    # volumes:
    #   - ./services/auth-service:/home/node/app
    depends_on:
      - rabbitmq
    networks:
      - app-network

  sync-service:
    build:
      context: ./services/sync-service
      dockerfile: ./docker/Dockerfile.dev
      args:
        RABBITMQ_HOST: ${RABBITMQ_HOST}
    environment:
      NODE_ENV: ${NODE_ENV}
      MESSAGE_QUEUE: amqp://rabbitmq
    # volumes:
    #   - ./services/sync-service:/home/node/app
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run dev'
    depends_on:
      - rabbitmq
    networks:
      - app-network
networks:
  app-network:
    driver: bridge