# Stage 1: Build
FROM node:18-alpine as builder

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY . .

RUN npm install

RUN npm run build

# Stage 2: Run
FROM node:18-alpine as runner

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --from=builder /home/node/app/dist ./dist

COPY --from=builder /home/node/app/package.json ./package.json

RUN npm install --only=production

CMD ["node", "dist/app.js"]