FROM node:18

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

ARG RABBITMQ_HOST

ENV RABBITMQ_HOST=${RABBITMQ_HOST}

COPY --chown=node:node package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "dev"]